name: hello

on:
  push:
    paths:
      - "hello/Dockerfile"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hello
  CACHE_NAME: /tmp/.hello-buildx-cache

jobs:
  bio_io_generate_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          labels: |
            org.opencontainers.image.title=hello
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short,prefix=,suffix=

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_NAME }}
          key: ${{ runner.os }}-buildx-${{ env.IMAGE_NAME }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ env.IMAGE_NAME }}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./hello
          file: ./hello/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=${{ env.CACHE_NAME }}
          cache-to: type=local,dest=${{ env.CACHE_NAME }}-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf ${{ env.CACHE_NAME }}
          mv ${{ env.CACHE_NAME }}-new ${{ env.CACHE_NAME }}
